#
# Marcio Ribeiro <marcio.ribeiro@maps.com.br> 
# Started: Tue Sep  6 21:44:42 BRT 2011
#

PDFLATEX ?= /usr/bin/pdflatex 

FILE = regex-20110906

all:
	$(PDFLATEX) $(FILE).tex

clean:
	rm -f $(FILE).aux $(FILE).log $(FILE).out $(FILE).pdf $(FILE).snm $(FILE).toc

